server:
  port: 8088
spring:
  datasource:
    username: root
    password: wangjun
    url: jdbc:mysql://localhost:3306/wangjun?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      idle-timeout: 60000
      maximum-pool-size: 30
      minimum-idle: 10
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.wj: debug

